AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
AWS_REGION: ${self:provider.region}
AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}

TWITTER_API_KEY: ${env:TWITTER_API_KEY}
TWITTER_API_KEY_SECRET: ${env:TWITTER_API_KEY_SECRET}

REDIS_HOSTNAME: ${env:REDIS_HOSTNAME}
REDIS_PORT: ${env:REDIS_PORT, "6379"}
REDIS_PASSWORD: ${env:REDIS_PASSWORD, ""}
REDIS_DB: ${env:REDIS_DB, 0}

MAIL_DRIVER: ${env:MAIL_DRIVER}
MAILTRAP_HOST: ${env:MAILTRAP_HOST, ""}
MAILTRAP_PORT: ${env:MAILTRAP_PORT, ""}
MAILTRAP_USERNAME: ${env:MAILTRAP_USERNAME, ""}
MAILTRAP_PASSWORD: ${env:MAILTRAP_PASSWORD, ""}
SENDGRID_HOST: ${env:SENDGRID_HOST, ""}
SENDGRID_PORT: ${env:SENDGRID_PORT, ""}
SENDGRID_USERNAME: ${env:SENDGRID_USERNAME, ""}
SENDGRID_PASSWORD: ${env:SENDGRID_PASSWORD, ""}

SESSION_SECRET: ${env:SESSION_SECRET}
APP_ENV: ${env:APP_ENV}
BASE_URL: ${env:BASE_URL}

CLOUDWATCH_METRICS: ${env:CLOUDWATCH_METRICS, "on"}
HONEYBADGER_API_KEY: ${env:HONEYBADGER_API_KEY}
NEW_RELIC_API_KEY: ${env:NEW_RELIC_API_KEY, ""}

ZEARCH_ENDPOINT: ${env:ZEARCH_ENDPOINT, ""}
ZEARCH_KEY: ${env:ZEARCH_KEY, ""}