name: Checks

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby Tests (Ruby 2.7)
    steps:
      - uses: actions/checkout@v2
      - name: Use Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: bundle install
      - name: Tests
        run: bundle exec rspec