name: Checks

on:
  push:
  pull_request:

jobs:
  nodejs_test:
    runs-on: ubuntu-latest
    name: Node.js Tests (Node.js 16.x)
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.5.0
      - run: npm ci --production=false
      - run: npm i puppeteer
      - name: Tests
        run: npm test

  ruby_test:
    runs-on: ubuntu-latest
    name: Ruby Tests (Ruby 2.7)
    steps:
      - uses: actions/checkout@v2
      - name: Use Ruby 2.7
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 2.7
      - run: bundle install
      - name: Tests
        run: bundle exec rspec