name: Deploy

# on:
#   workflow_run:
#     workflows: ["Checks"]
#     branches: [master]
#     types:
#       - completed

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    name: Deploy to prod
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - run: sls deploy
        # env:
        #   DEPLOY_URL: ${{ secrets.FORGE_DEPLOY_URL }}